# Action from https://github.com/gautamkrishnar/blog-post-workflow
name: Latest Starred Repos
on:
  schedule:
    # Runs every hour
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-github:
    name: Update this repo's README with starred repos from github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "GITHUB_STAR"
          max_post_count: "10"
          feed_list: "https://rsshub.app/github/starred_repos/cowbe0x004"
